// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQjAaWvsbOOKRE7uJxSpIQBuhNH1zVWQ',
    appId: '1:299087368802:web:024d0777ab65345240373b',
    messagingSenderId: '299087368802',
    projectId: 'loginst-d0120',
    authDomain: 'loginst-d0120.firebaseapp.com',
    storageBucket: 'loginst-d0120.firebasestorage.app',
    measurementId: 'G-NRD04NY72V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJtrCOnkqafx5REzVxfcdbqr0y6EA2F8',
    appId: '1:299087368802:android:d99580fd8f0906a140373b',
    messagingSenderId: '299087368802',
    projectId: 'loginst-d0120',
    storageBucket: 'loginst-d0120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlmjsOIAUOfzdhnjL0UtYtsczuUUFly7g',
    appId: '1:299087368802:ios:413796c6b2754d4240373b',
    messagingSenderId: '299087368802',
    projectId: 'loginst-d0120',
    storageBucket: 'loginst-d0120.firebasestorage.app',
    iosBundleId: 'com.example.fsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlmjsOIAUOfzdhnjL0UtYtsczuUUFly7g',
    appId: '1:299087368802:ios:413796c6b2754d4240373b',
    messagingSenderId: '299087368802',
    projectId: 'loginst-d0120',
    storageBucket: 'loginst-d0120.firebasestorage.app',
    iosBundleId: 'com.example.fsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQjAaWvsbOOKRE7uJxSpIQBuhNH1zVWQ',
    appId: '1:299087368802:web:477bdf0bc90388c540373b',
    messagingSenderId: '299087368802',
    projectId: 'loginst-d0120',
    authDomain: 'loginst-d0120.firebaseapp.com',
    storageBucket: 'loginst-d0120.firebasestorage.app',
    measurementId: 'G-QJEV3GH16N',
  );
}
